apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-controller
  template:
    metadata:
      labels:
        app: stock-controller
    spec:
      containers:
      - name: stock-controller
        image: ghcr.io/georgep1ckers/tracey-reloaded-stock-controller:latest
        ports:
        - containerPort: 8081
        env:
          - name: KUBE_NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          - name: OTEL_HOST
            value: "$(KUBE_NODE_NAME):4317"
---
apiVersion: v1
kind: Service
metadata:
  name: stock-controller
spec:
  selector:
    app: stock-controller
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081